# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: macos_test
    pool:
        vmImage: macos-latest
    steps:
    - script: |
        go version
    - script: |
        cd hello
        go build

  - job: windows_test
    pool:
        vmImage: windows-latest
    steps:
    - script: |
        go version
    - script: |
        cd hello
        go build

  - job: ubuntu_test
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        go version
    - script: |
        cd hello
        go build
